apiVersion: apps/v1
kind: Deployment
metadata:
  name: juypter-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: juypter-demo
  template:
    metadata:
      labels:
        app: juypter-demo
    spec:
      containers:
        - name: juypter-demo
          image: farberg/adm-jupyter
          imagePullPolicy: Always
          securityContext:
            runAsUser: 0
          env:
            - name: "JUPYTER_ENABLE_LAB"
              value: "yes"
            - name: "GRANT_SUDO"
              value: "yes"
          command:
            - "start-notebook.sh"
          args:
            - "--NotebookApp.token=''"
            - "--NotebookApp.password=''"

---
kind: Service
apiVersion: v1
metadata:
  name: juypter-demo-service
spec:
  selector:
    app: juypter-demo
  ports:
    - protocol: TCP
      port: 8888
      targetPort: 8888

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: popular-slides-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: juypter-demo-service
                port:
                  number: 8888